/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routers/__root'
import { Route as NoFooterLayoutRouteImport } from './routers/_noFooterLayout'
import { Route as MasterLayoutRouteImport } from './routers/_masterLayout'
import { Route as AuthLayoutRouteImport } from './routers/_authLayout'
import { Route as IndexRouteImport } from './routers/index'
import { Route as MasterLayoutProfileRouteImport } from './routers/_masterLayout/profile'
import { Route as NoFooterLayoutMapIndexRouteImport } from './routers/_noFooterLayout/map/index'
import { Route as MasterLayoutTasksIndexRouteImport } from './routers/_masterLayout/tasks/index'
import { Route as MasterLayoutSkillsIndexRouteImport } from './routers/_masterLayout/skills/index'
import { Route as MasterLayoutProjectsIndexRouteImport } from './routers/_masterLayout/projects/index'
import { Route as MasterLayoutProfileIndexRouteImport } from './routers/_masterLayout/profile/index'
import { Route as MasterLayoutOrganizationsIndexRouteImport } from './routers/_masterLayout/organizations/index'
import { Route as MasterLayoutEventsIndexRouteImport } from './routers/_masterLayout/events/index'
import { Route as MasterLayoutCategoriesIndexRouteImport } from './routers/_masterLayout/categories/index'
import { Route as MasterLayoutActivitiesIndexRouteImport } from './routers/_masterLayout/activities/index'
import { Route as MasterLayoutTasksIdIndexRouteImport } from './routers/_masterLayout/tasks/$id/index'
import { Route as MasterLayoutProjectsIdIndexRouteImport } from './routers/_masterLayout/projects/$id/index'
import { Route as MasterLayoutProfileSettingsIndexRouteImport } from './routers/_masterLayout/profile/settings/index'
import { Route as MasterLayoutOrganizationsIdIndexRouteImport } from './routers/_masterLayout/organizations/$id/index'
import { Route as MasterLayoutEventsIdIndexRouteImport } from './routers/_masterLayout/events/$id/index'
import { Route as MasterLayoutCategoriesIdIndexRouteImport } from './routers/_masterLayout/categories/$id/index'
import { Route as MasterLayoutActivitiesMyIndexRouteImport } from './routers/_masterLayout/activities/my/index'

const MultiStepFormIndexLazyRouteImport = createFileRoute('/multi-step-form/')()
const AuthLayoutAuthIndexLazyRouteImport =
  createFileRoute('/_authLayout/auth/')()
const AuthLayoutAuthVerificationTwoFactorLazyRouteImport = createFileRoute(
  '/_authLayout/auth/verification-two-factor',
)()
const AuthLayoutAuthVerificationEmailLazyRouteImport = createFileRoute(
  '/_authLayout/auth/verification-email',
)()
const AuthLayoutAuthForgotPasswordIndexLazyRouteImport = createFileRoute(
  '/_authLayout/auth/forgot-password/',
)()
const AuthLayoutAuthForgotPasswordVerificationLazyRouteImport = createFileRoute(
  '/_authLayout/auth/forgot-password/verification',
)()
const AuthLayoutAuthForgotPasswordSetPasswordLazyRouteImport = createFileRoute(
  '/_authLayout/auth/forgot-password/set-password',
)()

const NoFooterLayoutRoute = NoFooterLayoutRouteImport.update({
  id: '/_noFooterLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterLayoutRoute = MasterLayoutRouteImport.update({
  id: '/_masterLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiStepFormIndexLazyRoute = MultiStepFormIndexLazyRouteImport.update({
  id: '/multi-step-form/',
  path: '/multi-step-form/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routers/multi-step-form/index.lazy').then((d) => d.Route),
)
const MasterLayoutProfileRoute = MasterLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MasterLayoutRoute,
} as any)
const AuthLayoutAuthIndexLazyRoute = AuthLayoutAuthIndexLazyRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./routers/_authLayout/auth/index.lazy').then((d) => d.Route),
)
const NoFooterLayoutMapIndexRoute = NoFooterLayoutMapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => NoFooterLayoutRoute,
} as any).lazy(() =>
  import('./routers/_noFooterLayout/map/index.lazy').then((d) => d.Route),
)
const MasterLayoutTasksIndexRoute = MasterLayoutTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => MasterLayoutRoute,
} as any).lazy(() =>
  import('./routers/_masterLayout/tasks/index.lazy').then((d) => d.Route),
)
const MasterLayoutSkillsIndexRoute = MasterLayoutSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => MasterLayoutRoute,
} as any).lazy(() =>
  import('./routers/_masterLayout/skills/index.lazy').then((d) => d.Route),
)
const MasterLayoutProjectsIndexRoute =
  MasterLayoutProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => MasterLayoutRoute,
  } as any).lazy(() =>
    import('./routers/_masterLayout/projects/index.lazy').then((d) => d.Route),
  )
const MasterLayoutProfileIndexRoute =
  MasterLayoutProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MasterLayoutProfileRoute,
  } as any).lazy(() =>
    import('./routers/_masterLayout/profile/index.lazy').then((d) => d.Route),
  )
const MasterLayoutOrganizationsIndexRoute =
  MasterLayoutOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => MasterLayoutRoute,
  } as any).lazy(() =>
    import('./routers/_masterLayout/organizations/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MasterLayoutEventsIndexRoute = MasterLayoutEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => MasterLayoutRoute,
} as any).lazy(() =>
  import('./routers/_masterLayout/events/index.lazy').then((d) => d.Route),
)
const MasterLayoutCategoriesIndexRoute =
  MasterLayoutCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => MasterLayoutRoute,
  } as any).lazy(() =>
    import('./routers/_masterLayout/categories/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MasterLayoutActivitiesIndexRoute =
  MasterLayoutActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => MasterLayoutRoute,
  } as any)
const AuthLayoutAuthVerificationTwoFactorLazyRoute =
  AuthLayoutAuthVerificationTwoFactorLazyRouteImport.update({
    id: '/auth/verification-two-factor',
    path: '/auth/verification-two-factor',
    getParentRoute: () => AuthLayoutRoute,
  } as any).lazy(() =>
    import('./routers/_authLayout/auth/verification-two-factor.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthLayoutAuthVerificationEmailLazyRoute =
  AuthLayoutAuthVerificationEmailLazyRouteImport.update({
    id: '/auth/verification-email',
    path: '/auth/verification-email',
    getParentRoute: () => AuthLayoutRoute,
  } as any).lazy(() =>
    import('./routers/_authLayout/auth/verification-email.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthLayoutAuthForgotPasswordIndexLazyRoute =
  AuthLayoutAuthForgotPasswordIndexLazyRouteImport.update({
    id: '/auth/forgot-password/',
    path: '/auth/forgot-password/',
    getParentRoute: () => AuthLayoutRoute,
  } as any).lazy(() =>
    import('./routers/_authLayout/auth/forgot-password/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MasterLayoutTasksIdIndexRoute =
  MasterLayoutTasksIdIndexRouteImport.update({
    id: '/tasks/$id/',
    path: '/tasks/$id/',
    getParentRoute: () => MasterLayoutRoute,
  } as any)
const MasterLayoutProjectsIdIndexRoute =
  MasterLayoutProjectsIdIndexRouteImport.update({
    id: '/projects/$id/',
    path: '/projects/$id/',
    getParentRoute: () => MasterLayoutRoute,
  } as any).lazy(() =>
    import('./routers/_masterLayout/projects/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MasterLayoutProfileSettingsIndexRoute =
  MasterLayoutProfileSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => MasterLayoutProfileRoute,
  } as any).lazy(() =>
    import('./routers/_masterLayout/profile/settings/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MasterLayoutOrganizationsIdIndexRoute =
  MasterLayoutOrganizationsIdIndexRouteImport.update({
    id: '/organizations/$id/',
    path: '/organizations/$id/',
    getParentRoute: () => MasterLayoutRoute,
  } as any)
const MasterLayoutEventsIdIndexRoute =
  MasterLayoutEventsIdIndexRouteImport.update({
    id: '/events/$id/',
    path: '/events/$id/',
    getParentRoute: () => MasterLayoutRoute,
  } as any)
const MasterLayoutCategoriesIdIndexRoute =
  MasterLayoutCategoriesIdIndexRouteImport.update({
    id: '/categories/$id/',
    path: '/categories/$id/',
    getParentRoute: () => MasterLayoutRoute,
  } as any).lazy(() =>
    import('./routers/_masterLayout/categories/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MasterLayoutActivitiesMyIndexRoute =
  MasterLayoutActivitiesMyIndexRouteImport.update({
    id: '/activities/my/',
    path: '/activities/my/',
    getParentRoute: () => MasterLayoutRoute,
  } as any).lazy(() =>
    import('./routers/_masterLayout/activities/my/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthLayoutAuthForgotPasswordVerificationLazyRoute =
  AuthLayoutAuthForgotPasswordVerificationLazyRouteImport.update({
    id: '/auth/forgot-password/verification',
    path: '/auth/forgot-password/verification',
    getParentRoute: () => AuthLayoutRoute,
  } as any).lazy(() =>
    import('./routers/_authLayout/auth/forgot-password/verification.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthLayoutAuthForgotPasswordSetPasswordLazyRoute =
  AuthLayoutAuthForgotPasswordSetPasswordLazyRouteImport.update({
    id: '/auth/forgot-password/set-password',
    path: '/auth/forgot-password/set-password',
    getParentRoute: () => AuthLayoutRoute,
  } as any).lazy(() =>
    import('./routers/_authLayout/auth/forgot-password/set-password.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof MasterLayoutProfileRouteWithChildren
  '/multi-step-form/': typeof MultiStepFormIndexLazyRoute
  '/auth/verification-email': typeof AuthLayoutAuthVerificationEmailLazyRoute
  '/auth/verification-two-factor': typeof AuthLayoutAuthVerificationTwoFactorLazyRoute
  '/activities/': typeof MasterLayoutActivitiesIndexRoute
  '/categories/': typeof MasterLayoutCategoriesIndexRoute
  '/events/': typeof MasterLayoutEventsIndexRoute
  '/organizations/': typeof MasterLayoutOrganizationsIndexRoute
  '/profile/': typeof MasterLayoutProfileIndexRoute
  '/projects/': typeof MasterLayoutProjectsIndexRoute
  '/skills/': typeof MasterLayoutSkillsIndexRoute
  '/tasks/': typeof MasterLayoutTasksIndexRoute
  '/map/': typeof NoFooterLayoutMapIndexRoute
  '/auth/': typeof AuthLayoutAuthIndexLazyRoute
  '/auth/forgot-password/set-password': typeof AuthLayoutAuthForgotPasswordSetPasswordLazyRoute
  '/auth/forgot-password/verification': typeof AuthLayoutAuthForgotPasswordVerificationLazyRoute
  '/activities/my/': typeof MasterLayoutActivitiesMyIndexRoute
  '/categories/$id/': typeof MasterLayoutCategoriesIdIndexRoute
  '/events/$id/': typeof MasterLayoutEventsIdIndexRoute
  '/organizations/$id/': typeof MasterLayoutOrganizationsIdIndexRoute
  '/profile/settings/': typeof MasterLayoutProfileSettingsIndexRoute
  '/projects/$id/': typeof MasterLayoutProjectsIdIndexRoute
  '/tasks/$id/': typeof MasterLayoutTasksIdIndexRoute
  '/auth/forgot-password/': typeof AuthLayoutAuthForgotPasswordIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/multi-step-form': typeof MultiStepFormIndexLazyRoute
  '/auth/verification-email': typeof AuthLayoutAuthVerificationEmailLazyRoute
  '/auth/verification-two-factor': typeof AuthLayoutAuthVerificationTwoFactorLazyRoute
  '/activities': typeof MasterLayoutActivitiesIndexRoute
  '/categories': typeof MasterLayoutCategoriesIndexRoute
  '/events': typeof MasterLayoutEventsIndexRoute
  '/organizations': typeof MasterLayoutOrganizationsIndexRoute
  '/profile': typeof MasterLayoutProfileIndexRoute
  '/projects': typeof MasterLayoutProjectsIndexRoute
  '/skills': typeof MasterLayoutSkillsIndexRoute
  '/tasks': typeof MasterLayoutTasksIndexRoute
  '/map': typeof NoFooterLayoutMapIndexRoute
  '/auth': typeof AuthLayoutAuthIndexLazyRoute
  '/auth/forgot-password/set-password': typeof AuthLayoutAuthForgotPasswordSetPasswordLazyRoute
  '/auth/forgot-password/verification': typeof AuthLayoutAuthForgotPasswordVerificationLazyRoute
  '/activities/my': typeof MasterLayoutActivitiesMyIndexRoute
  '/categories/$id': typeof MasterLayoutCategoriesIdIndexRoute
  '/events/$id': typeof MasterLayoutEventsIdIndexRoute
  '/organizations/$id': typeof MasterLayoutOrganizationsIdIndexRoute
  '/profile/settings': typeof MasterLayoutProfileSettingsIndexRoute
  '/projects/$id': typeof MasterLayoutProjectsIdIndexRoute
  '/tasks/$id': typeof MasterLayoutTasksIdIndexRoute
  '/auth/forgot-password': typeof AuthLayoutAuthForgotPasswordIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_masterLayout': typeof MasterLayoutRouteWithChildren
  '/_noFooterLayout': typeof NoFooterLayoutRouteWithChildren
  '/_masterLayout/profile': typeof MasterLayoutProfileRouteWithChildren
  '/multi-step-form/': typeof MultiStepFormIndexLazyRoute
  '/_authLayout/auth/verification-email': typeof AuthLayoutAuthVerificationEmailLazyRoute
  '/_authLayout/auth/verification-two-factor': typeof AuthLayoutAuthVerificationTwoFactorLazyRoute
  '/_masterLayout/activities/': typeof MasterLayoutActivitiesIndexRoute
  '/_masterLayout/categories/': typeof MasterLayoutCategoriesIndexRoute
  '/_masterLayout/events/': typeof MasterLayoutEventsIndexRoute
  '/_masterLayout/organizations/': typeof MasterLayoutOrganizationsIndexRoute
  '/_masterLayout/profile/': typeof MasterLayoutProfileIndexRoute
  '/_masterLayout/projects/': typeof MasterLayoutProjectsIndexRoute
  '/_masterLayout/skills/': typeof MasterLayoutSkillsIndexRoute
  '/_masterLayout/tasks/': typeof MasterLayoutTasksIndexRoute
  '/_noFooterLayout/map/': typeof NoFooterLayoutMapIndexRoute
  '/_authLayout/auth/': typeof AuthLayoutAuthIndexLazyRoute
  '/_authLayout/auth/forgot-password/set-password': typeof AuthLayoutAuthForgotPasswordSetPasswordLazyRoute
  '/_authLayout/auth/forgot-password/verification': typeof AuthLayoutAuthForgotPasswordVerificationLazyRoute
  '/_masterLayout/activities/my/': typeof MasterLayoutActivitiesMyIndexRoute
  '/_masterLayout/categories/$id/': typeof MasterLayoutCategoriesIdIndexRoute
  '/_masterLayout/events/$id/': typeof MasterLayoutEventsIdIndexRoute
  '/_masterLayout/organizations/$id/': typeof MasterLayoutOrganizationsIdIndexRoute
  '/_masterLayout/profile/settings/': typeof MasterLayoutProfileSettingsIndexRoute
  '/_masterLayout/projects/$id/': typeof MasterLayoutProjectsIdIndexRoute
  '/_masterLayout/tasks/$id/': typeof MasterLayoutTasksIdIndexRoute
  '/_authLayout/auth/forgot-password/': typeof AuthLayoutAuthForgotPasswordIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/multi-step-form/'
    | '/auth/verification-email'
    | '/auth/verification-two-factor'
    | '/activities/'
    | '/categories/'
    | '/events/'
    | '/organizations/'
    | '/profile/'
    | '/projects/'
    | '/skills/'
    | '/tasks/'
    | '/map/'
    | '/auth/'
    | '/auth/forgot-password/set-password'
    | '/auth/forgot-password/verification'
    | '/activities/my/'
    | '/categories/$id/'
    | '/events/$id/'
    | '/organizations/$id/'
    | '/profile/settings/'
    | '/projects/$id/'
    | '/tasks/$id/'
    | '/auth/forgot-password/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/multi-step-form'
    | '/auth/verification-email'
    | '/auth/verification-two-factor'
    | '/activities'
    | '/categories'
    | '/events'
    | '/organizations'
    | '/profile'
    | '/projects'
    | '/skills'
    | '/tasks'
    | '/map'
    | '/auth'
    | '/auth/forgot-password/set-password'
    | '/auth/forgot-password/verification'
    | '/activities/my'
    | '/categories/$id'
    | '/events/$id'
    | '/organizations/$id'
    | '/profile/settings'
    | '/projects/$id'
    | '/tasks/$id'
    | '/auth/forgot-password'
  id:
    | '__root__'
    | '/'
    | '/_authLayout'
    | '/_masterLayout'
    | '/_noFooterLayout'
    | '/_masterLayout/profile'
    | '/multi-step-form/'
    | '/_authLayout/auth/verification-email'
    | '/_authLayout/auth/verification-two-factor'
    | '/_masterLayout/activities/'
    | '/_masterLayout/categories/'
    | '/_masterLayout/events/'
    | '/_masterLayout/organizations/'
    | '/_masterLayout/profile/'
    | '/_masterLayout/projects/'
    | '/_masterLayout/skills/'
    | '/_masterLayout/tasks/'
    | '/_noFooterLayout/map/'
    | '/_authLayout/auth/'
    | '/_authLayout/auth/forgot-password/set-password'
    | '/_authLayout/auth/forgot-password/verification'
    | '/_masterLayout/activities/my/'
    | '/_masterLayout/categories/$id/'
    | '/_masterLayout/events/$id/'
    | '/_masterLayout/organizations/$id/'
    | '/_masterLayout/profile/settings/'
    | '/_masterLayout/projects/$id/'
    | '/_masterLayout/tasks/$id/'
    | '/_authLayout/auth/forgot-password/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  MasterLayoutRoute: typeof MasterLayoutRouteWithChildren
  NoFooterLayoutRoute: typeof NoFooterLayoutRouteWithChildren
  MultiStepFormIndexLazyRoute: typeof MultiStepFormIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_noFooterLayout': {
      id: '/_noFooterLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NoFooterLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_masterLayout': {
      id: '/_masterLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MasterLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-step-form/': {
      id: '/multi-step-form/'
      path: '/multi-step-form'
      fullPath: '/multi-step-form/'
      preLoaderRoute: typeof MultiStepFormIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_masterLayout/profile': {
      id: '/_masterLayout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MasterLayoutProfileRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_authLayout/auth/': {
      id: '/_authLayout/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthLayoutAuthIndexLazyRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_noFooterLayout/map/': {
      id: '/_noFooterLayout/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof NoFooterLayoutMapIndexRouteImport
      parentRoute: typeof NoFooterLayoutRoute
    }
    '/_masterLayout/tasks/': {
      id: '/_masterLayout/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof MasterLayoutTasksIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_masterLayout/skills/': {
      id: '/_masterLayout/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof MasterLayoutSkillsIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_masterLayout/projects/': {
      id: '/_masterLayout/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof MasterLayoutProjectsIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_masterLayout/profile/': {
      id: '/_masterLayout/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof MasterLayoutProfileIndexRouteImport
      parentRoute: typeof MasterLayoutProfileRoute
    }
    '/_masterLayout/organizations/': {
      id: '/_masterLayout/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof MasterLayoutOrganizationsIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_masterLayout/events/': {
      id: '/_masterLayout/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof MasterLayoutEventsIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_masterLayout/categories/': {
      id: '/_masterLayout/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof MasterLayoutCategoriesIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_masterLayout/activities/': {
      id: '/_masterLayout/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof MasterLayoutActivitiesIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_authLayout/auth/verification-two-factor': {
      id: '/_authLayout/auth/verification-two-factor'
      path: '/auth/verification-two-factor'
      fullPath: '/auth/verification-two-factor'
      preLoaderRoute: typeof AuthLayoutAuthVerificationTwoFactorLazyRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/verification-email': {
      id: '/_authLayout/auth/verification-email'
      path: '/auth/verification-email'
      fullPath: '/auth/verification-email'
      preLoaderRoute: typeof AuthLayoutAuthVerificationEmailLazyRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/forgot-password/': {
      id: '/_authLayout/auth/forgot-password/'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password/'
      preLoaderRoute: typeof AuthLayoutAuthForgotPasswordIndexLazyRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_masterLayout/tasks/$id/': {
      id: '/_masterLayout/tasks/$id/'
      path: '/tasks/$id'
      fullPath: '/tasks/$id/'
      preLoaderRoute: typeof MasterLayoutTasksIdIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_masterLayout/projects/$id/': {
      id: '/_masterLayout/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof MasterLayoutProjectsIdIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_masterLayout/profile/settings/': {
      id: '/_masterLayout/profile/settings/'
      path: '/settings'
      fullPath: '/profile/settings/'
      preLoaderRoute: typeof MasterLayoutProfileSettingsIndexRouteImport
      parentRoute: typeof MasterLayoutProfileRoute
    }
    '/_masterLayout/organizations/$id/': {
      id: '/_masterLayout/organizations/$id/'
      path: '/organizations/$id'
      fullPath: '/organizations/$id/'
      preLoaderRoute: typeof MasterLayoutOrganizationsIdIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_masterLayout/events/$id/': {
      id: '/_masterLayout/events/$id/'
      path: '/events/$id'
      fullPath: '/events/$id/'
      preLoaderRoute: typeof MasterLayoutEventsIdIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_masterLayout/categories/$id/': {
      id: '/_masterLayout/categories/$id/'
      path: '/categories/$id'
      fullPath: '/categories/$id/'
      preLoaderRoute: typeof MasterLayoutCategoriesIdIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_masterLayout/activities/my/': {
      id: '/_masterLayout/activities/my/'
      path: '/activities/my'
      fullPath: '/activities/my/'
      preLoaderRoute: typeof MasterLayoutActivitiesMyIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_authLayout/auth/forgot-password/verification': {
      id: '/_authLayout/auth/forgot-password/verification'
      path: '/auth/forgot-password/verification'
      fullPath: '/auth/forgot-password/verification'
      preLoaderRoute: typeof AuthLayoutAuthForgotPasswordVerificationLazyRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/forgot-password/set-password': {
      id: '/_authLayout/auth/forgot-password/set-password'
      path: '/auth/forgot-password/set-password'
      fullPath: '/auth/forgot-password/set-password'
      preLoaderRoute: typeof AuthLayoutAuthForgotPasswordSetPasswordLazyRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutAuthVerificationEmailLazyRoute: typeof AuthLayoutAuthVerificationEmailLazyRoute
  AuthLayoutAuthVerificationTwoFactorLazyRoute: typeof AuthLayoutAuthVerificationTwoFactorLazyRoute
  AuthLayoutAuthIndexLazyRoute: typeof AuthLayoutAuthIndexLazyRoute
  AuthLayoutAuthForgotPasswordSetPasswordLazyRoute: typeof AuthLayoutAuthForgotPasswordSetPasswordLazyRoute
  AuthLayoutAuthForgotPasswordVerificationLazyRoute: typeof AuthLayoutAuthForgotPasswordVerificationLazyRoute
  AuthLayoutAuthForgotPasswordIndexLazyRoute: typeof AuthLayoutAuthForgotPasswordIndexLazyRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAuthVerificationEmailLazyRoute:
    AuthLayoutAuthVerificationEmailLazyRoute,
  AuthLayoutAuthVerificationTwoFactorLazyRoute:
    AuthLayoutAuthVerificationTwoFactorLazyRoute,
  AuthLayoutAuthIndexLazyRoute: AuthLayoutAuthIndexLazyRoute,
  AuthLayoutAuthForgotPasswordSetPasswordLazyRoute:
    AuthLayoutAuthForgotPasswordSetPasswordLazyRoute,
  AuthLayoutAuthForgotPasswordVerificationLazyRoute:
    AuthLayoutAuthForgotPasswordVerificationLazyRoute,
  AuthLayoutAuthForgotPasswordIndexLazyRoute:
    AuthLayoutAuthForgotPasswordIndexLazyRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface MasterLayoutProfileRouteChildren {
  MasterLayoutProfileIndexRoute: typeof MasterLayoutProfileIndexRoute
  MasterLayoutProfileSettingsIndexRoute: typeof MasterLayoutProfileSettingsIndexRoute
}

const MasterLayoutProfileRouteChildren: MasterLayoutProfileRouteChildren = {
  MasterLayoutProfileIndexRoute: MasterLayoutProfileIndexRoute,
  MasterLayoutProfileSettingsIndexRoute: MasterLayoutProfileSettingsIndexRoute,
}

const MasterLayoutProfileRouteWithChildren =
  MasterLayoutProfileRoute._addFileChildren(MasterLayoutProfileRouteChildren)

interface MasterLayoutRouteChildren {
  MasterLayoutProfileRoute: typeof MasterLayoutProfileRouteWithChildren
  MasterLayoutActivitiesIndexRoute: typeof MasterLayoutActivitiesIndexRoute
  MasterLayoutCategoriesIndexRoute: typeof MasterLayoutCategoriesIndexRoute
  MasterLayoutEventsIndexRoute: typeof MasterLayoutEventsIndexRoute
  MasterLayoutOrganizationsIndexRoute: typeof MasterLayoutOrganizationsIndexRoute
  MasterLayoutProjectsIndexRoute: typeof MasterLayoutProjectsIndexRoute
  MasterLayoutSkillsIndexRoute: typeof MasterLayoutSkillsIndexRoute
  MasterLayoutTasksIndexRoute: typeof MasterLayoutTasksIndexRoute
  MasterLayoutActivitiesMyIndexRoute: typeof MasterLayoutActivitiesMyIndexRoute
  MasterLayoutCategoriesIdIndexRoute: typeof MasterLayoutCategoriesIdIndexRoute
  MasterLayoutEventsIdIndexRoute: typeof MasterLayoutEventsIdIndexRoute
  MasterLayoutOrganizationsIdIndexRoute: typeof MasterLayoutOrganizationsIdIndexRoute
  MasterLayoutProjectsIdIndexRoute: typeof MasterLayoutProjectsIdIndexRoute
  MasterLayoutTasksIdIndexRoute: typeof MasterLayoutTasksIdIndexRoute
}

const MasterLayoutRouteChildren: MasterLayoutRouteChildren = {
  MasterLayoutProfileRoute: MasterLayoutProfileRouteWithChildren,
  MasterLayoutActivitiesIndexRoute: MasterLayoutActivitiesIndexRoute,
  MasterLayoutCategoriesIndexRoute: MasterLayoutCategoriesIndexRoute,
  MasterLayoutEventsIndexRoute: MasterLayoutEventsIndexRoute,
  MasterLayoutOrganizationsIndexRoute: MasterLayoutOrganizationsIndexRoute,
  MasterLayoutProjectsIndexRoute: MasterLayoutProjectsIndexRoute,
  MasterLayoutSkillsIndexRoute: MasterLayoutSkillsIndexRoute,
  MasterLayoutTasksIndexRoute: MasterLayoutTasksIndexRoute,
  MasterLayoutActivitiesMyIndexRoute: MasterLayoutActivitiesMyIndexRoute,
  MasterLayoutCategoriesIdIndexRoute: MasterLayoutCategoriesIdIndexRoute,
  MasterLayoutEventsIdIndexRoute: MasterLayoutEventsIdIndexRoute,
  MasterLayoutOrganizationsIdIndexRoute: MasterLayoutOrganizationsIdIndexRoute,
  MasterLayoutProjectsIdIndexRoute: MasterLayoutProjectsIdIndexRoute,
  MasterLayoutTasksIdIndexRoute: MasterLayoutTasksIdIndexRoute,
}

const MasterLayoutRouteWithChildren = MasterLayoutRoute._addFileChildren(
  MasterLayoutRouteChildren,
)

interface NoFooterLayoutRouteChildren {
  NoFooterLayoutMapIndexRoute: typeof NoFooterLayoutMapIndexRoute
}

const NoFooterLayoutRouteChildren: NoFooterLayoutRouteChildren = {
  NoFooterLayoutMapIndexRoute: NoFooterLayoutMapIndexRoute,
}

const NoFooterLayoutRouteWithChildren = NoFooterLayoutRoute._addFileChildren(
  NoFooterLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  MasterLayoutRoute: MasterLayoutRouteWithChildren,
  NoFooterLayoutRoute: NoFooterLayoutRouteWithChildren,
  MultiStepFormIndexLazyRoute: MultiStepFormIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
