/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routers/__root'
import { Route as NoFooterLayoutRouteImport } from './routers/_noFooterLayout'
import { Route as MasterLayoutRouteImport } from './routers/_masterLayout'
import { Route as AuthLayoutRouteImport } from './routers/_authLayout'
import { Route as IndexRouteImport } from './routers/index'
import { Route as MultiStepFormIndexRouteImport } from './routers/multi-step-form/index'
import { Route as MasterLayoutProfileRouteImport } from './routers/_masterLayout/profile'
import { Route as NoFooterLayoutMapIndexRouteImport } from './routers/_noFooterLayout/map/index'
import { Route as MasterLayoutSkillsIndexRouteImport } from './routers/_masterLayout/skills/index'
import { Route as MasterLayoutProjectsIndexRouteImport } from './routers/_masterLayout/projects/index'
import { Route as MasterLayoutProfileIndexRouteImport } from './routers/_masterLayout/profile/index'
import { Route as MasterLayoutCategoriesIndexRouteImport } from './routers/_masterLayout/categories/index'
import { Route as AuthLayoutAuthIndexRouteImport } from './routers/_authLayout/auth/index'
import { Route as AuthLayoutAuthVerificationTwoFactorRouteImport } from './routers/_authLayout/auth/verification-two-factor'
import { Route as AuthLayoutAuthVerificationEmailRouteImport } from './routers/_authLayout/auth/verification-email'
import { Route as MasterLayoutProjectsMyIndexRouteImport } from './routers/_masterLayout/projects/my/index'
import { Route as MasterLayoutProjectsIdIndexRouteImport } from './routers/_masterLayout/projects/$id/index'
import { Route as MasterLayoutProfileSettingsIndexRouteImport } from './routers/_masterLayout/profile/settings/index'
import { Route as MasterLayoutCategoriesIdIndexRouteImport } from './routers/_masterLayout/categories/$id/index'
import { Route as AuthLayoutAuthForgotPasswordIndexRouteImport } from './routers/_authLayout/auth/forgot-password/index'
import { Route as AuthLayoutAuthForgotPasswordVerificationRouteImport } from './routers/_authLayout/auth/forgot-password/verification'
import { Route as AuthLayoutAuthForgotPasswordSetPasswordRouteImport } from './routers/_authLayout/auth/forgot-password/set-password'

const NoFooterLayoutRoute = NoFooterLayoutRouteImport.update({
  id: '/_noFooterLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterLayoutRoute = MasterLayoutRouteImport.update({
  id: '/_masterLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiStepFormIndexRoute = MultiStepFormIndexRouteImport.update({
  id: '/multi-step-form/',
  path: '/multi-step-form/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterLayoutProfileRoute = MasterLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MasterLayoutRoute,
} as any)
const NoFooterLayoutMapIndexRoute = NoFooterLayoutMapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => NoFooterLayoutRoute,
} as any)
const MasterLayoutSkillsIndexRoute = MasterLayoutSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => MasterLayoutRoute,
} as any)
const MasterLayoutProjectsIndexRoute =
  MasterLayoutProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => MasterLayoutRoute,
  } as any)
const MasterLayoutProfileIndexRoute =
  MasterLayoutProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MasterLayoutProfileRoute,
  } as any)
const MasterLayoutCategoriesIndexRoute =
  MasterLayoutCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => MasterLayoutRoute,
  } as any)
const AuthLayoutAuthIndexRoute = AuthLayoutAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAuthVerificationTwoFactorRoute =
  AuthLayoutAuthVerificationTwoFactorRouteImport.update({
    id: '/auth/verification-two-factor',
    path: '/auth/verification-two-factor',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAuthVerificationEmailRoute =
  AuthLayoutAuthVerificationEmailRouteImport.update({
    id: '/auth/verification-email',
    path: '/auth/verification-email',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const MasterLayoutProjectsMyIndexRoute =
  MasterLayoutProjectsMyIndexRouteImport.update({
    id: '/projects/my/',
    path: '/projects/my/',
    getParentRoute: () => MasterLayoutRoute,
  } as any)
const MasterLayoutProjectsIdIndexRoute =
  MasterLayoutProjectsIdIndexRouteImport.update({
    id: '/projects/$id/',
    path: '/projects/$id/',
    getParentRoute: () => MasterLayoutRoute,
  } as any)
const MasterLayoutProfileSettingsIndexRoute =
  MasterLayoutProfileSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => MasterLayoutProfileRoute,
  } as any)
const MasterLayoutCategoriesIdIndexRoute =
  MasterLayoutCategoriesIdIndexRouteImport.update({
    id: '/categories/$id/',
    path: '/categories/$id/',
    getParentRoute: () => MasterLayoutRoute,
  } as any)
const AuthLayoutAuthForgotPasswordIndexRoute =
  AuthLayoutAuthForgotPasswordIndexRouteImport.update({
    id: '/auth/forgot-password/',
    path: '/auth/forgot-password/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAuthForgotPasswordVerificationRoute =
  AuthLayoutAuthForgotPasswordVerificationRouteImport.update({
    id: '/auth/forgot-password/verification',
    path: '/auth/forgot-password/verification',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutAuthForgotPasswordSetPasswordRoute =
  AuthLayoutAuthForgotPasswordSetPasswordRouteImport.update({
    id: '/auth/forgot-password/set-password',
    path: '/auth/forgot-password/set-password',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof MasterLayoutProfileRouteWithChildren
  '/multi-step-form/': typeof MultiStepFormIndexRoute
  '/auth/verification-email': typeof AuthLayoutAuthVerificationEmailRoute
  '/auth/verification-two-factor': typeof AuthLayoutAuthVerificationTwoFactorRoute
  '/auth/': typeof AuthLayoutAuthIndexRoute
  '/categories/': typeof MasterLayoutCategoriesIndexRoute
  '/profile/': typeof MasterLayoutProfileIndexRoute
  '/projects/': typeof MasterLayoutProjectsIndexRoute
  '/skills/': typeof MasterLayoutSkillsIndexRoute
  '/map/': typeof NoFooterLayoutMapIndexRoute
  '/auth/forgot-password/set-password': typeof AuthLayoutAuthForgotPasswordSetPasswordRoute
  '/auth/forgot-password/verification': typeof AuthLayoutAuthForgotPasswordVerificationRoute
  '/auth/forgot-password/': typeof AuthLayoutAuthForgotPasswordIndexRoute
  '/categories/$id/': typeof MasterLayoutCategoriesIdIndexRoute
  '/profile/settings/': typeof MasterLayoutProfileSettingsIndexRoute
  '/projects/$id/': typeof MasterLayoutProjectsIdIndexRoute
  '/projects/my/': typeof MasterLayoutProjectsMyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/multi-step-form': typeof MultiStepFormIndexRoute
  '/auth/verification-email': typeof AuthLayoutAuthVerificationEmailRoute
  '/auth/verification-two-factor': typeof AuthLayoutAuthVerificationTwoFactorRoute
  '/auth': typeof AuthLayoutAuthIndexRoute
  '/categories': typeof MasterLayoutCategoriesIndexRoute
  '/profile': typeof MasterLayoutProfileIndexRoute
  '/projects': typeof MasterLayoutProjectsIndexRoute
  '/skills': typeof MasterLayoutSkillsIndexRoute
  '/map': typeof NoFooterLayoutMapIndexRoute
  '/auth/forgot-password/set-password': typeof AuthLayoutAuthForgotPasswordSetPasswordRoute
  '/auth/forgot-password/verification': typeof AuthLayoutAuthForgotPasswordVerificationRoute
  '/auth/forgot-password': typeof AuthLayoutAuthForgotPasswordIndexRoute
  '/categories/$id': typeof MasterLayoutCategoriesIdIndexRoute
  '/profile/settings': typeof MasterLayoutProfileSettingsIndexRoute
  '/projects/$id': typeof MasterLayoutProjectsIdIndexRoute
  '/projects/my': typeof MasterLayoutProjectsMyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/_masterLayout': typeof MasterLayoutRouteWithChildren
  '/_noFooterLayout': typeof NoFooterLayoutRouteWithChildren
  '/_masterLayout/profile': typeof MasterLayoutProfileRouteWithChildren
  '/multi-step-form/': typeof MultiStepFormIndexRoute
  '/_authLayout/auth/verification-email': typeof AuthLayoutAuthVerificationEmailRoute
  '/_authLayout/auth/verification-two-factor': typeof AuthLayoutAuthVerificationTwoFactorRoute
  '/_authLayout/auth/': typeof AuthLayoutAuthIndexRoute
  '/_masterLayout/categories/': typeof MasterLayoutCategoriesIndexRoute
  '/_masterLayout/profile/': typeof MasterLayoutProfileIndexRoute
  '/_masterLayout/projects/': typeof MasterLayoutProjectsIndexRoute
  '/_masterLayout/skills/': typeof MasterLayoutSkillsIndexRoute
  '/_noFooterLayout/map/': typeof NoFooterLayoutMapIndexRoute
  '/_authLayout/auth/forgot-password/set-password': typeof AuthLayoutAuthForgotPasswordSetPasswordRoute
  '/_authLayout/auth/forgot-password/verification': typeof AuthLayoutAuthForgotPasswordVerificationRoute
  '/_authLayout/auth/forgot-password/': typeof AuthLayoutAuthForgotPasswordIndexRoute
  '/_masterLayout/categories/$id/': typeof MasterLayoutCategoriesIdIndexRoute
  '/_masterLayout/profile/settings/': typeof MasterLayoutProfileSettingsIndexRoute
  '/_masterLayout/projects/$id/': typeof MasterLayoutProjectsIdIndexRoute
  '/_masterLayout/projects/my/': typeof MasterLayoutProjectsMyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/multi-step-form/'
    | '/auth/verification-email'
    | '/auth/verification-two-factor'
    | '/auth/'
    | '/categories/'
    | '/profile/'
    | '/projects/'
    | '/skills/'
    | '/map/'
    | '/auth/forgot-password/set-password'
    | '/auth/forgot-password/verification'
    | '/auth/forgot-password/'
    | '/categories/$id/'
    | '/profile/settings/'
    | '/projects/$id/'
    | '/projects/my/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/multi-step-form'
    | '/auth/verification-email'
    | '/auth/verification-two-factor'
    | '/auth'
    | '/categories'
    | '/profile'
    | '/projects'
    | '/skills'
    | '/map'
    | '/auth/forgot-password/set-password'
    | '/auth/forgot-password/verification'
    | '/auth/forgot-password'
    | '/categories/$id'
    | '/profile/settings'
    | '/projects/$id'
    | '/projects/my'
  id:
    | '__root__'
    | '/'
    | '/_authLayout'
    | '/_masterLayout'
    | '/_noFooterLayout'
    | '/_masterLayout/profile'
    | '/multi-step-form/'
    | '/_authLayout/auth/verification-email'
    | '/_authLayout/auth/verification-two-factor'
    | '/_authLayout/auth/'
    | '/_masterLayout/categories/'
    | '/_masterLayout/profile/'
    | '/_masterLayout/projects/'
    | '/_masterLayout/skills/'
    | '/_noFooterLayout/map/'
    | '/_authLayout/auth/forgot-password/set-password'
    | '/_authLayout/auth/forgot-password/verification'
    | '/_authLayout/auth/forgot-password/'
    | '/_masterLayout/categories/$id/'
    | '/_masterLayout/profile/settings/'
    | '/_masterLayout/projects/$id/'
    | '/_masterLayout/projects/my/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  MasterLayoutRoute: typeof MasterLayoutRouteWithChildren
  NoFooterLayoutRoute: typeof NoFooterLayoutRouteWithChildren
  MultiStepFormIndexRoute: typeof MultiStepFormIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_noFooterLayout': {
      id: '/_noFooterLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NoFooterLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_masterLayout': {
      id: '/_masterLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MasterLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-step-form/': {
      id: '/multi-step-form/'
      path: '/multi-step-form'
      fullPath: '/multi-step-form/'
      preLoaderRoute: typeof MultiStepFormIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_masterLayout/profile': {
      id: '/_masterLayout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MasterLayoutProfileRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_noFooterLayout/map/': {
      id: '/_noFooterLayout/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof NoFooterLayoutMapIndexRouteImport
      parentRoute: typeof NoFooterLayoutRoute
    }
    '/_masterLayout/skills/': {
      id: '/_masterLayout/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof MasterLayoutSkillsIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_masterLayout/projects/': {
      id: '/_masterLayout/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof MasterLayoutProjectsIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_masterLayout/profile/': {
      id: '/_masterLayout/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof MasterLayoutProfileIndexRouteImport
      parentRoute: typeof MasterLayoutProfileRoute
    }
    '/_masterLayout/categories/': {
      id: '/_masterLayout/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof MasterLayoutCategoriesIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_authLayout/auth/': {
      id: '/_authLayout/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthLayoutAuthIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/verification-two-factor': {
      id: '/_authLayout/auth/verification-two-factor'
      path: '/auth/verification-two-factor'
      fullPath: '/auth/verification-two-factor'
      preLoaderRoute: typeof AuthLayoutAuthVerificationTwoFactorRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/verification-email': {
      id: '/_authLayout/auth/verification-email'
      path: '/auth/verification-email'
      fullPath: '/auth/verification-email'
      preLoaderRoute: typeof AuthLayoutAuthVerificationEmailRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_masterLayout/projects/my/': {
      id: '/_masterLayout/projects/my/'
      path: '/projects/my'
      fullPath: '/projects/my/'
      preLoaderRoute: typeof MasterLayoutProjectsMyIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_masterLayout/projects/$id/': {
      id: '/_masterLayout/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof MasterLayoutProjectsIdIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_masterLayout/profile/settings/': {
      id: '/_masterLayout/profile/settings/'
      path: '/settings'
      fullPath: '/profile/settings/'
      preLoaderRoute: typeof MasterLayoutProfileSettingsIndexRouteImport
      parentRoute: typeof MasterLayoutProfileRoute
    }
    '/_masterLayout/categories/$id/': {
      id: '/_masterLayout/categories/$id/'
      path: '/categories/$id'
      fullPath: '/categories/$id/'
      preLoaderRoute: typeof MasterLayoutCategoriesIdIndexRouteImport
      parentRoute: typeof MasterLayoutRoute
    }
    '/_authLayout/auth/forgot-password/': {
      id: '/_authLayout/auth/forgot-password/'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password/'
      preLoaderRoute: typeof AuthLayoutAuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/forgot-password/verification': {
      id: '/_authLayout/auth/forgot-password/verification'
      path: '/auth/forgot-password/verification'
      fullPath: '/auth/forgot-password/verification'
      preLoaderRoute: typeof AuthLayoutAuthForgotPasswordVerificationRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/forgot-password/set-password': {
      id: '/_authLayout/auth/forgot-password/set-password'
      path: '/auth/forgot-password/set-password'
      fullPath: '/auth/forgot-password/set-password'
      preLoaderRoute: typeof AuthLayoutAuthForgotPasswordSetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutAuthVerificationEmailRoute: typeof AuthLayoutAuthVerificationEmailRoute
  AuthLayoutAuthVerificationTwoFactorRoute: typeof AuthLayoutAuthVerificationTwoFactorRoute
  AuthLayoutAuthIndexRoute: typeof AuthLayoutAuthIndexRoute
  AuthLayoutAuthForgotPasswordSetPasswordRoute: typeof AuthLayoutAuthForgotPasswordSetPasswordRoute
  AuthLayoutAuthForgotPasswordVerificationRoute: typeof AuthLayoutAuthForgotPasswordVerificationRoute
  AuthLayoutAuthForgotPasswordIndexRoute: typeof AuthLayoutAuthForgotPasswordIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAuthVerificationEmailRoute: AuthLayoutAuthVerificationEmailRoute,
  AuthLayoutAuthVerificationTwoFactorRoute:
    AuthLayoutAuthVerificationTwoFactorRoute,
  AuthLayoutAuthIndexRoute: AuthLayoutAuthIndexRoute,
  AuthLayoutAuthForgotPasswordSetPasswordRoute:
    AuthLayoutAuthForgotPasswordSetPasswordRoute,
  AuthLayoutAuthForgotPasswordVerificationRoute:
    AuthLayoutAuthForgotPasswordVerificationRoute,
  AuthLayoutAuthForgotPasswordIndexRoute:
    AuthLayoutAuthForgotPasswordIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface MasterLayoutProfileRouteChildren {
  MasterLayoutProfileIndexRoute: typeof MasterLayoutProfileIndexRoute
  MasterLayoutProfileSettingsIndexRoute: typeof MasterLayoutProfileSettingsIndexRoute
}

const MasterLayoutProfileRouteChildren: MasterLayoutProfileRouteChildren = {
  MasterLayoutProfileIndexRoute: MasterLayoutProfileIndexRoute,
  MasterLayoutProfileSettingsIndexRoute: MasterLayoutProfileSettingsIndexRoute,
}

const MasterLayoutProfileRouteWithChildren =
  MasterLayoutProfileRoute._addFileChildren(MasterLayoutProfileRouteChildren)

interface MasterLayoutRouteChildren {
  MasterLayoutProfileRoute: typeof MasterLayoutProfileRouteWithChildren
  MasterLayoutCategoriesIndexRoute: typeof MasterLayoutCategoriesIndexRoute
  MasterLayoutProjectsIndexRoute: typeof MasterLayoutProjectsIndexRoute
  MasterLayoutSkillsIndexRoute: typeof MasterLayoutSkillsIndexRoute
  MasterLayoutCategoriesIdIndexRoute: typeof MasterLayoutCategoriesIdIndexRoute
  MasterLayoutProjectsIdIndexRoute: typeof MasterLayoutProjectsIdIndexRoute
  MasterLayoutProjectsMyIndexRoute: typeof MasterLayoutProjectsMyIndexRoute
}

const MasterLayoutRouteChildren: MasterLayoutRouteChildren = {
  MasterLayoutProfileRoute: MasterLayoutProfileRouteWithChildren,
  MasterLayoutCategoriesIndexRoute: MasterLayoutCategoriesIndexRoute,
  MasterLayoutProjectsIndexRoute: MasterLayoutProjectsIndexRoute,
  MasterLayoutSkillsIndexRoute: MasterLayoutSkillsIndexRoute,
  MasterLayoutCategoriesIdIndexRoute: MasterLayoutCategoriesIdIndexRoute,
  MasterLayoutProjectsIdIndexRoute: MasterLayoutProjectsIdIndexRoute,
  MasterLayoutProjectsMyIndexRoute: MasterLayoutProjectsMyIndexRoute,
}

const MasterLayoutRouteWithChildren = MasterLayoutRoute._addFileChildren(
  MasterLayoutRouteChildren,
)

interface NoFooterLayoutRouteChildren {
  NoFooterLayoutMapIndexRoute: typeof NoFooterLayoutMapIndexRoute
}

const NoFooterLayoutRouteChildren: NoFooterLayoutRouteChildren = {
  NoFooterLayoutMapIndexRoute: NoFooterLayoutMapIndexRoute,
}

const NoFooterLayoutRouteWithChildren = NoFooterLayoutRoute._addFileChildren(
  NoFooterLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  MasterLayoutRoute: MasterLayoutRouteWithChildren,
  NoFooterLayoutRoute: NoFooterLayoutRouteWithChildren,
  MultiStepFormIndexRoute: MultiStepFormIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
