import type { Organization } from "../model/types";

export type RawOrganization = Partial<Organization> & {
  Id?: string;
  Name?: string;
  Description?: string;
  OwnerId?: string;
  owner?: unknown;
  Owner?: unknown;
  CreatedAt?: string;
  LaunchDate?: string | null;
  StartAt?: string | null;
  LogoUrl?: string | null;
  ContactEmail?: string | null;
  Website?: string | null;
  PhoneNumber?: string | null;
  LocationInfo?: Organization["locationInfo"];
  JoinPolicy?: string | null;
  LeavePolicy?: string | null;
  SocialLinks?: unknown[];
  IsArchived?: boolean;
  Categories?: unknown[];
  Rating?: number;
  TotalTasks?: number;
  ActiveTasks?: number;
  ActiveProjects?: number;
  ActiveEvents?: number;
  Level?: number;
  ShareUrl?: string;
  membersCount?: number;
  MemberCount?: number;
  MembersCount?: number;
  MemberPreviews?: unknown[];
  TotalActivities?: number;
  ActiveCount?: number;
  progress?: unknown;
  Progress?: unknown;
  Members?: unknown[];
  TeamMembers?: unknown[];
  members?: unknown[];
  teamMembers?: unknown[];
};
