import {
  Ban,
  ChartBar,
  ClipboardList,
  Coins,
  Tag,
  Users,
} from "lucide-react";
import type { QuickAccessItem } from "../model/types";

export const quickAccessItems: QuickAccessItem[] = [
  {
    title: "Users",
    description: "Search accounts, view summaries, manage roles platform-wide.",
    href: "/admin/users",
    icon: Users,
    tone: "users",
    footerSource: "users",
    footerTone: "neutral",
    footerAction: "accounts в†’",
  },
  {
    title: "Bans",
    description: "Review active bans, revoke early with a recorded reason.",
    href: "/admin/bans",
    icon: Ban,
    tone: "bans",
    footerSource: "bans",
    footerTone: "danger",
    footerAction: "active в†’",
  },
  {
    title: "Time bank",
    description: "Adjust balances manually and view platform-wide statistics.",
    href: "/admin/time-bank",
    icon: Coins,
    tone: "timeBank",
    footerSource: "timeBank",
    footerTone: "neutral",
    footerAction: "volume в†’",
  },
  {
    title: "Skills",
    description: "Create, verify, and manage the platform skills registry.",
    href: "/admin/skills",
    icon: Tag,
    tone: "skills",
    footerSource: "skills",
    footerTone: "neutral",
    footerAction: "in registry в†’",
  },
  {
    title: "Requests",
    description: "Category, skill, and appeal requests awaiting a decision.",
    href: "/admin/requests",
    icon: ClipboardList,
    tone: "requests",
    footerSource: "requests",
    footerTone: "warning",
    footerAction: "pending в†’",
  },
  {
    title: "Statistics",
    description: "Platform-wide growth, activity, and engagement metrics.",
    href: "/admin/statistics",
    icon: ChartBar,
    tone: "statistics",
    footerAction: "View report в†’",
  },
];
